#!/usr/bin/env bash
# Centralized constants for local-openclaw scripts.
# Override any value via the corresponding environment variable.
# Safe to source multiple times — does not use readonly.

# --- Fixed targets ---
OPENCLAW_TARGET_OKX="${TARGET_OKX:-https://www.okx.com}"
OPENCLAW_TARGET_LOCAL="${TARGET_LOCAL:-http://127.0.0.1:8000}"

# --- Orchestrator ---
OPENCLAW_ORCH_BASE_URL="${ORCH_BASE_URL:-http://127.0.0.1:18000}"

# --- Timeouts & windows ---
OPENCLAW_TIMEOUT_SECONDS="${OPENCLAW_TIMEOUT_SECONDS:-1800}"
OPENCLAW_OBSERVATION_SECONDS="${OBSERVATION_SECONDS:-300}"
OPENCLAW_API_TIMEOUT_SECONDS="${OPENCLAW_API_TIMEOUT_SECONDS:-15}"

# --- Benchmark ---
OPENCLAW_BENCHMARK_HISTORY_SIZE="${OPENCLAW_BENCHMARK_HISTORY_SIZE:-10}"
OPENCLAW_BENCHMARK_TREND_WINDOW="${OPENCLAW_BENCHMARK_TREND_WINDOW:-5}"
OPENCLAW_BENCHMARK_MIN_HISTORY="${OPENCLAW_BENCHMARK_MIN_HISTORY:-3}"

# --- Crawler health alert thresholds ---
OPENCLAW_ALERT_MIN_CASES="${OPENCLAW_ALERT_MIN_CASES:-10}"
OPENCLAW_ALERT_MIN_OBSERVED="${OPENCLAW_ALERT_MIN_OBSERVED:-5}"
OPENCLAW_ALERT_KATANA_MIN_LINES="${OPENCLAW_ALERT_KATANA_MIN_LINES:-25}"
OPENCLAW_ALERT_CRAWLER_COVERAGE_RATIO="${OPENCLAW_ALERT_CRAWLER_COVERAGE_RATIO:-2}"

# --- Token management ---
OPENCLAW_TOKEN_REFRESH_COOLDOWN_SECONDS="${OPENCLAW_TOKEN_REFRESH_COOLDOWN_SECONDS:-30}"
OPENCLAW_SESSION_TTL_HOURS="${ORCH_SESSION_TTL_HOURS:-24}"

# --- Healthy-skip marker ---
OPENCLAW_HEALTHY_SKIP_MARKER="NO_ACTIONABLE_BUG_HEALTHY_RUNS"

# --- Log rotation ---
OPENCLAW_LOG_MAX_BYTES="${OPENCLAW_LOG_MAX_BYTES:-10485760}"  # 10MB
