#!/usr/bin/env bash
# Centralized constants for local-hermes-agent scripts.
# Override any value via the corresponding environment variable.
# Safe to source multiple times — does not use readonly.

# --- Fixed targets ---
HERMES_TARGET_OKX="${TARGET_OKX:-https://www.okx.com}"
HERMES_TARGET_LOCAL="${TARGET_LOCAL:-http://127.0.0.1:8000}"

# --- Orchestrator ---
HERMES_ORCH_BASE_URL="${ORCH_BASE_URL:-http://127.0.0.1:18000}"

# --- Timeouts & windows ---
HERMES_TIMEOUT_SECONDS="${HERMES_TIMEOUT_SECONDS:-1800}"
HERMES_OBSERVATION_SECONDS="${OBSERVATION_SECONDS:-300}"
HERMES_API_TIMEOUT_SECONDS="${HERMES_API_TIMEOUT_SECONDS:-15}"

# --- Benchmark ---
HERMES_BENCHMARK_HISTORY_SIZE="${HERMES_BENCHMARK_HISTORY_SIZE:-10}"
HERMES_BENCHMARK_TREND_WINDOW="${HERMES_BENCHMARK_TREND_WINDOW:-5}"
HERMES_BENCHMARK_MIN_HISTORY="${HERMES_BENCHMARK_MIN_HISTORY:-3}"

# --- Crawler health alert thresholds ---
HERMES_ALERT_MIN_CASES="${HERMES_ALERT_MIN_CASES:-10}"
HERMES_ALERT_MIN_OBSERVED="${HERMES_ALERT_MIN_OBSERVED:-5}"
HERMES_ALERT_KATANA_MIN_LINES="${HERMES_ALERT_KATANA_MIN_LINES:-25}"
HERMES_ALERT_CRAWLER_COVERAGE_RATIO="${HERMES_ALERT_CRAWLER_COVERAGE_RATIO:-2}"

# --- Token management ---
HERMES_TOKEN_REFRESH_COOLDOWN_SECONDS="${HERMES_TOKEN_REFRESH_COOLDOWN_SECONDS:-30}"
HERMES_SESSION_TTL_HOURS="${ORCH_SESSION_TTL_HOURS:-24}"

# --- Healthy-skip marker ---
HERMES_HEALTHY_SKIP_MARKER="NO_ACTIONABLE_BUG_HEALTHY_RUNS"

# --- Log rotation ---
HERMES_LOG_MAX_BYTES="${HERMES_LOG_MAX_BYTES:-10485760}"  # 10MB
